genome_size: 2506966135
effective_size: 2497530654
reps: [CP, GS]
tissues: [Liver, Lamina]
assays: [Nuclei, Tissue, NucleiAM, TissueAM]
reads: [R1, R2]
ref: /home/pengsc/reference/equcab3/UCSC/equCab3.fa.gz
